### ISSUE TITLE
Remove comma dangle

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/eslint-config-gitbook#1]
On a suggestion from @AaronO , we could remove `comma-dangle`, or even set it to `always-multiline`. Trailing commas are incompatible with a lot of browsers, but since we are transpiling the code anyway...

Current value: https://github.com/GitbookIO/eslint-config-gitbook/blob/master/index.js#L99

Spec: http://eslint.org/docs/rules/comma-dangle

**Comment by jpreynat** [comment]
👎  Sorry :)

**Comment by SamyPesse** [comment]
:-1: sorry :)

**Comment by Soreine** [comment]
"Your argument is invalid, I used an emoji" :p

But okay :)
